# Generated by Django 5.0 on 2023-12-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_type', models.CharField(choices=[('private', 'private'), ('public', 'public'), ('Other', 'Other')], max_length=20)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
